package com.jvn.core.animation;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

/**
 * Shared vocabulary for Puppeteer/JES timeline actions.
 *
 * <p>The parser, diagnostics, and JES bridge should agree on this contract so
 * timeline code generated by Puppeteer can be reopened, embedded in JES, and
 * registered for runtime playback without dialect drift.</p>
 */
public final class TimelineActionSchema {
    private static final Map<String, ActionSpec> ACTIONS;

    public record ActionSpec(String name, Set<String> keys, Map<String, String> keyAliases) {
        public ActionSpec {
            name = name == null ? "" : name.trim();
            keys = Collections.unmodifiableSet(new LinkedHashSet<>(keys != null ? keys : Set.of()));
            keyAliases = Collections.unmodifiableMap(new LinkedHashMap<>(keyAliases != null ? keyAliases : Map.of()));
        }

        public boolean allowsKey(String key) {
            String normalized = normalize(key);
            return keys.contains(normalized) || keyAliases.containsKey(normalized);
        }

        public String canonicalKey(String key) {
            String normalized = normalize(key);
            return keyAliases.getOrDefault(normalized, normalized);
        }

        public Set<String> acceptedKeys() {
            LinkedHashSet<String> accepted = new LinkedHashSet<>(keys);
            accepted.addAll(keyAliases.keySet());
            return Collections.unmodifiableSet(accepted);
        }
    }

    static {
        Map<String, ActionSpec> actions = new LinkedHashMap<>();
        register(actions, "move", keys("x", "y", "dur", "easing", "interp"), aliases("duration", "dur"));
        register(actions, "depth", keys("z", "dur", "easing", "interp"), aliases("duration", "dur"));
        register(actions, "pivot", keys("ox", "oy", "dur", "easing", "interp"), aliases("duration", "dur"));
        register(actions, "rotate", keys("deg", "dur", "easing", "interp"),
            aliases("duration", "dur", "angle", "deg", "rotation", "deg"));
        register(actions, "scale", keys("sx", "sy", "dur", "easing", "interp"),
            aliases("duration", "dur", "x", "sx", "y", "sy", "scale_x", "sx", "scale_y", "sy"));
        register(actions, "mirror", keys("mirrorx", "dur", "easing", "interp"),
            aliases("duration", "dur", "mirror_x", "mirrorx", "flipx", "mirrorx", "flip_x", "mirrorx", "x", "mirrorx", "value", "mirrorx"));
        register(actions, "fade", keys("alpha", "dur", "easing", "interp"), aliases("duration", "dur"));
        register(actions, "visible", keys("value", "visible"), Map.of("visible", "value"));
        register(actions, "expression", keys("value", "path", "position", "target"), Map.of());
        register(actions, "show", keys("target", "expression", "value", "path", "position", "layer"), Map.of());
        register(actions, "hide", keys("target"), Map.of());
        register(actions, "replace", keys("target", "expression", "value", "path"), Map.of());
        register(actions, "scene", keys("target", "id", "path", "value"), Map.of());
        register(actions, "cameraMove", keys("x", "y", "dur", "easing", "interp"), aliases("duration", "dur"));
        register(actions, "cameraZoom", keys("zoom", "dur", "easing", "interp"), aliases("duration", "dur"));
        register(actions, "event", Set.of(), Map.of());
        register(actions, "property", keys("key", "value", "dur", "easing", "interp"), aliases("duration", "dur"));
        register(actions, "playAudio", keys("id", "path", "channel", "volume", "loop", "bgm", "fadeinms"),
            aliases("fadein_ms", "fadeinms", "fadein", "fadeinms", "fade_in", "fadeinms"));
        register(actions, "parallel", Set.of(), Map.of());
        register(actions, "timeline", Set.of(), Map.of());
        register(actions, "wait", Set.of("ms"), Map.of());
        ACTIONS = Collections.unmodifiableMap(actions);
    }

    private TimelineActionSchema() {
    }

    public static boolean isKnownAction(String action) {
        return ACTIONS.containsKey(normalize(action));
    }

    public static Set<String> knownActions() {
        return Collections.unmodifiableSet(ACTIONS.keySet());
    }

    public static ActionSpec spec(String action) {
        return ACTIONS.get(normalize(action));
    }

    public static boolean isKnownKey(String action, String key) {
        ActionSpec spec = spec(action);
        return spec != null && spec.allowsKey(key);
    }

    public static String canonicalKey(String action, String key) {
        ActionSpec spec = spec(action);
        return spec != null ? spec.canonicalKey(key) : normalize(key);
    }

    public static Set<String> acceptedKeys(String action) {
        ActionSpec spec = spec(action);
        return spec != null ? spec.acceptedKeys() : Set.of();
    }

    public static String normalize(String value) {
        return value == null ? "" : value.trim().toLowerCase(Locale.ROOT);
    }

    private static void register(Map<String, ActionSpec> actions, String name, Set<String> keys, Map<String, String> aliases) {
        actions.put(normalize(name), new ActionSpec(name, lowerSet(keys), lowerMap(aliases)));
    }

    private static Set<String> keys(String... values) {
        LinkedHashSet<String> out = new LinkedHashSet<>();
        if (values != null) {
            Collections.addAll(out, values);
        }
        return out;
    }

    private static Map<String, String> aliases(String... pairs) {
        LinkedHashMap<String, String> out = new LinkedHashMap<>();
        if (pairs == null) return out;
        for (int i = 0; i + 1 < pairs.length; i += 2) {
            out.put(pairs[i], pairs[i + 1]);
        }
        return out;
    }

    private static Set<String> lowerSet(Set<String> values) {
        LinkedHashSet<String> out = new LinkedHashSet<>();
        if (values != null) {
            for (String value : values) {
                String normalized = normalize(value);
                if (!normalized.isBlank()) out.add(normalized);
            }
        }
        return out;
    }

    private static Map<String, String> lowerMap(Map<String, String> values) {
        LinkedHashMap<String, String> out = new LinkedHashMap<>();
        if (values != null) {
            for (Map.Entry<String, String> entry : values.entrySet()) {
                String key = normalize(entry.getKey());
                String value = normalize(entry.getValue());
                if (!key.isBlank() && !value.isBlank()) out.put(key, value);
            }
        }
        return out;
    }
}
