import java.security.MessageDigest

plugins {
  `java`
  application
  id("net.ltgt.errorprone") version "4.0.1"
}

dependencies {
  runtimeOnly("ch.qos.logback:logback-classic:1.5.6")

  errorprone("com.google.errorprone:error_prone_core:2.28.0")
  errorprone("com.uber.nullaway:nullaway:0.11.0")
}

tasks.withType<JavaCompile>().configureEach {
  (options as org.gradle.api.plugins.ExtensionAware).extensions
    .findByType(net.ltgt.gradle.errorprone.ErrorProneOptions::class.java)
    ?.also { ep ->
      ep.disableAllChecks.set(true)
      ep.check("NullAway", net.ltgt.gradle.errorprone.CheckSeverity.WARN)
      ep.option("NullAway:AnnotatedPackages", "com.jvn.hub")
    }
}

application {
  mainClass.set("com.jvn.hub.JvnHub")
}

// The hub is intentionally dependency-free: JDK Swing only.
// It shells out to ./gradlew and git as child processes.

// --- Generated version resource ---------------------------------------------
// Writes the project version into a properties file that the hub reads at
// startup so the UI can show "v<version>" without hardcoding it in code.
val generatedVersionDir = layout.buildDirectory.dir("generated-resources/version")

val generateHubVersionResource = tasks.register("generateHubVersionResource") {
  val outputDir = generatedVersionDir
  val versionString = rootProject.version.toString()
  inputs.property("version", versionString)
  outputs.dir(outputDir)
  doLast {
    val target = outputDir.get().asFile.resolve("com/jvn/hub/version.properties")
    target.parentFile.mkdirs()
    target.writeText(
      """
      |# Auto-generated by :hub:generateHubVersionResource. Do not edit by hand.
      |version=$versionString
      |""".trimMargin()
    )
  }
}

sourceSets.named("main") {
  resources.srcDir(generatedVersionDir)
}

tasks.named("processResources") {
  dependsOn(generateHubVersionResource)
}

tasks.named<JavaExec>("run") {
  // Run from the project root so relative paths (gradlew, .git) resolve naturally.
  workingDir = rootProject.projectDir
  // Propagate the root into the forked JVM; JvnHub reads this to anchor every
  // child-process (gradlew, git) invocation regardless of where the user launched from.
  systemProperty("jvn.projectRoot", rootProject.projectDir.absolutePath)
  // Keep the launching console quiet: the hub is a GUI.
  standardInput = System.`in`
}

val packagedEngineWorkspaceZip = tasks.register<Zip>("packagedEngineWorkspaceZip") {
  group = "distribution"
  description = "Zips a clean engine workspace for the self-contained Engine Hub jar."
  archiveFileName.set("packaged-engine-workspace.zip")
  destinationDirectory.set(layout.buildDirectory.dir("packaged-engine"))
  isZip64 = true

  from(rootProject.rootDir) {
    into("engine")
    includeEmptyDirs = false
    exclude(
        ".git/**",
        ".gradle/**",
        ".jvn-gradle-user-home/**",
        ".idea/**",
        ".vscode/**",
        "**/.DS_Store",
        "build/**",
        "**/build/**",
        "**/bin/**",
        "**/out/**",
        "**/target/**",
        "**/hs_err_pid*.log",
        "**/*.log",
        "**/.pytest_cache/**",
        "**/__pycache__/**",
        "tools/vscode-jvn/node_modules/**",
        "tools/vscode-jvn/*.vsix",
        "jvn",
        "jvn.bat",
        "jvn.desktop",
        "JVN.command")
  }
}

val packageEngineHubLiteJar = tasks.register<Jar>("packageEngineHubLiteJar") {
  group = "distribution"
  description = "Builds a smaller Hub jar without the warmed Gradle dependency cache."
  dependsOn(tasks.named("classes"), packagedEngineWorkspaceZip)
  archiveBaseName.set("jvn-engine-hub-lite")
  archiveVersion.set(rootProject.version.toString())
  destinationDirectory.set(rootProject.layout.buildDirectory.dir("distributions"))
  duplicatesStrategy = DuplicatesStrategy.EXCLUDE

  manifest {
    attributes(
        "Main-Class" to "com.jvn.hub.PackagedHubLauncher",
        "Implementation-Title" to "JVN Engine Hub",
        "Implementation-Version" to rootProject.version.toString())
  }

  from(sourceSets.main.get().output)
  from(packagedEngineWorkspaceZip) {
    into("com/jvn/hub")
    rename { "packaged-engine.zip" }
  }
}

val packagedGradleCacheHome = layout.buildDirectory.dir("packaged-gradle-cache/home")

val preparePackagedGradleCache = tasks.register<Exec>("preparePackagedGradleCache") {
  group = "distribution"
  description = "Warms an isolated Gradle user home for the cached Engine Hub jar."
  val cacheHome = packagedGradleCacheHome
  inputs.files(
      rootProject.layout.projectDirectory.file("settings.gradle.kts"),
      rootProject.layout.projectDirectory.file("build.gradle.kts"),
      rootProject.layout.projectDirectory.file("gradle.properties"))
  outputs.dir(cacheHome)

  doFirst {
    delete(cacheHome)
    cacheHome.get().asFile.mkdirs()
  }

  workingDir = rootProject.rootDir
  environment("GRADLE_USER_HOME", cacheHome.get().asFile.absolutePath)
  commandLine(
      if (System.getProperty("os.name").lowercase().contains("win")) "gradlew.bat" else "./gradlew",
      "--no-daemon",
      "--console=plain",
      ":core:compileJava",
      ":fx:compileJava",
      ":audio:compileJava",
      ":scripting:compileJava",
      ":runtime:compileJava",
      ":editor:compileJava",
      ":hub:compileJava",
      ":hub:dependencies",
      ":editor:dependencies",
      ":runtime:dependencies",
      "--configuration",
      "runtimeClasspath")
}

val stripPackagedGradleCache = tasks.register("stripPackagedGradleCache") {
  group = "distribution"
  description = "Removes volatile or machine-local files from the packaged Gradle cache."
  dependsOn(preparePackagedGradleCache)
  val cacheHome = packagedGradleCacheHome
  inputs.dir(cacheHome)
  outputs.dir(cacheHome)

  doLast {
    val home = cacheHome.get().asFile
    delete(
        home.resolve("daemon"),
        home.resolve("notifications"),
        home.resolve("workers"),
        home.resolve("caches/build-cache-1"),
        home.resolve("caches/journal-1"))
    home.resolve("caches").listFiles()
      ?.filter { it.isDirectory }
      ?.forEach { delete(it.resolve("transforms")) }
    fileTree(home) {
      include("**/*.lock")
      include("**/*.log")
      include("**/gc.properties")
      include("**/fileHashes.lock")
      include("**/executionHistory.lock")
      include("jdks/*.tar.gz")
      include("jdks/*.zip")
    }.files.forEach { delete(it) }
  }
}

val packagedGradleCacheZip = tasks.register<Zip>("packagedGradleCacheZip") {
  group = "distribution"
  description = "Zips the warmed Gradle dependency cache for the cached Engine Hub jar."
  dependsOn(stripPackagedGradleCache)
  archiveFileName.set("packaged-gradle-cache.zip")
  destinationDirectory.set(layout.buildDirectory.dir("packaged-engine"))
  isZip64 = true
  from(packagedGradleCacheHome) {
    into(".jvn-gradle-user-home")
    includeEmptyDirs = false
  }
}

val packageEngineHubJar = tasks.register<Jar>("packageEngineHubJar") {
  group = "distribution"
  description = "Builds the canonical, self-contained Engine Hub release jar."
  dependsOn(tasks.named("classes"), packagedEngineWorkspaceZip, packagedGradleCacheZip)
  archiveBaseName.set("jvn-engine-hub")
  archiveVersion.set(rootProject.version.toString())
  destinationDirectory.set(rootProject.layout.buildDirectory.dir("distributions"))
  duplicatesStrategy = DuplicatesStrategy.EXCLUDE

  manifest {
    attributes(
        "Main-Class" to "com.jvn.hub.PackagedHubLauncher",
        "Implementation-Title" to "JVN Engine Hub",
        "Implementation-Version" to rootProject.version.toString())
  }

  from(sourceSets.main.get().output)
  from(packagedEngineWorkspaceZip) {
    into("com/jvn/hub")
    rename { "packaged-engine.zip" }
  }
  from(packagedGradleCacheZip) {
    into("com/jvn/hub")
    rename { "packaged-gradle-cache.zip" }
  }
}

tasks.register("packageEngineHubJarWithCache") {
  group = "distribution"
  description = "Compatibility alias for packageEngineHubJar."
  dependsOn(packageEngineHubJar)
}

val packagedHubSmokeRoot = layout.buildDirectory.dir("tmp/verify-packaged-engine-hub")

val verifyPackagedEngineHubJar = tasks.register<Exec>("verifyPackagedEngineHubJar") {
  group = "verification"
  description = "Extracts the actual release jar and verifies its bundled engine workspace."
  dependsOn(packageEngineHubJar)

  val smokeRoot = packagedHubSmokeRoot
  val releaseJar = packageEngineHubJar.flatMap { it.archiveFile }
  inputs.file(releaseJar)
  outputs.dir(smokeRoot)

  doFirst {
    delete(smokeRoot)
    smokeRoot.get().asFile.mkdirs()
    commandLine(
        javaToolchains.launcherFor {
          languageVersion.set(JavaLanguageVersion.of(21))
        }.get().executablePath.asFile.absolutePath,
        "-Djvn.packagedEngineRoot=${smokeRoot.get().asFile.absolutePath}",
        "-jar",
        releaseJar.get().asFile.absolutePath,
        "--extract-only")
  }

  doLast {
    val extractedEngine = smokeRoot.get().asFile.walkTopDown()
      .firstOrNull { it.isDirectory && it.name == "engine" && File(it, "settings.gradle.kts").isFile }
      ?: throw GradleException("Packaged Hub did not extract a valid engine workspace")
    val requiredPaths = listOf(
        "gradlew",
        "gradlew.bat",
        "gradle/wrapper/gradle-wrapper.jar",
        "gradle/wrapper/gradle-wrapper.properties",
        "modules/hub/src/main/java/com/jvn/hub/JvnHub.java",
        "modules/editor/build.gradle.kts",
        "modules/runtime/build.gradle.kts",
        ".jvn-gradle-user-home")
    val missing = requiredPaths.filterNot { File(extractedEngine, it).exists() }
    if (missing.isNotEmpty()) {
      throw GradleException("Packaged Hub is missing: ${missing.joinToString()}")
    }
  }
}

val smokeTestPackagedEngineHubOffline = tasks.register<Exec>("smokeTestPackagedEngineHubOffline") {
  group = "verification"
  description = "Compiles the Hub from the extracted release workspace with networking disabled."
  dependsOn(verifyPackagedEngineHubJar)
  inputs.file(packageEngineHubJar.flatMap { it.archiveFile })

  doFirst {
    val extractedEngine = packagedHubSmokeRoot.get().asFile.walkTopDown()
      .firstOrNull { it.isDirectory && it.name == "engine" && File(it, "settings.gradle.kts").isFile }
      ?: throw GradleException("Packaged Hub smoke workspace is unavailable")
    environment("GRADLE_USER_HOME", File(extractedEngine, ".jvn-gradle-user-home").absolutePath)
    workingDir(extractedEngine)
    commandLine(
        File(extractedEngine, if (System.getProperty("os.name").lowercase().contains("win")) "gradlew.bat" else "gradlew").absolutePath,
        "--offline",
        "--no-daemon",
        "--console=plain",
        ":hub:classes",
        ":hub:dependencies",
        ":editor:dependencies",
        ":runtime:dependencies",
        "--configuration",
        "runtimeClasspath")
  }
}

val checksumEngineHubJar = tasks.register("checksumEngineHubJar") {
  group = "distribution"
  description = "Verifies the release jar and writes its SHA-256 checksum."
  dependsOn(smokeTestPackagedEngineHubOffline)
  val releaseJar = packageEngineHubJar.flatMap { it.archiveFile }
  val checksumFile = releaseJar.map { it.asFile.resolveSibling("${it.asFile.name}.sha256") }
  inputs.file(releaseJar)
  outputs.file(checksumFile)
  doLast {
    val jar = releaseJar.get().asFile
    val digest = MessageDigest.getInstance("SHA-256")
    jar.inputStream().buffered().use { input ->
      val buffer = ByteArray(DEFAULT_BUFFER_SIZE)
      while (true) {
        val count = input.read(buffer)
        if (count < 0) break
        digest.update(buffer, 0, count)
      }
    }
    val hash = digest.digest().joinToString("") { "%02x".format(it) }
    checksumFile.get().writeText("$hash  ${jar.name}\n")
  }
}

tasks.register("packageEngineHubRelease") {
  group = "distribution"
  description = "Builds, smoke-tests, and checksums the complete Engine Hub release jar."
  dependsOn(checksumEngineHubJar)
}
