plugins {
  `java`
  application
  id("net.ltgt.errorprone") version "4.0.1"
}

dependencies {
  runtimeOnly("ch.qos.logback:logback-classic:1.5.6")

  errorprone("com.google.errorprone:error_prone_core:2.28.0")
  errorprone("com.uber.nullaway:nullaway:0.11.0")
}

tasks.withType<JavaCompile>().configureEach {
  (options as org.gradle.api.plugins.ExtensionAware).extensions
    .findByType(net.ltgt.gradle.errorprone.ErrorProneOptions::class.java)
    ?.also { ep ->
      ep.disableAllChecks.set(true)
      ep.check("NullAway", net.ltgt.gradle.errorprone.CheckSeverity.WARN)
      ep.option("NullAway:AnnotatedPackages", "com.jvn.hub")
    }
}

application {
  mainClass.set("com.jvn.hub.JvnHub")
}

// The hub is intentionally dependency-free: JDK Swing only.
// It shells out to ./gradlew and git as child processes.

// --- Generated version resource ---------------------------------------------
// Writes the project version into a properties file that the hub reads at
// startup so the UI can show "v<version>" without hardcoding it in code.
val generatedVersionDir = layout.buildDirectory.dir("generated-resources/version")

val generateHubVersionResource = tasks.register("generateHubVersionResource") {
  val outputDir = generatedVersionDir
  val versionString = rootProject.version.toString()
  inputs.property("version", versionString)
  outputs.dir(outputDir)
  doLast {
    val target = outputDir.get().asFile.resolve("com/jvn/hub/version.properties")
    target.parentFile.mkdirs()
    target.writeText(
      """
      |# Auto-generated by :hub:generateHubVersionResource. Do not edit by hand.
      |version=$versionString
      |""".trimMargin()
    )
  }
}

sourceSets.named("main") {
  resources.srcDir(generatedVersionDir)
}

tasks.named("processResources") {
  dependsOn(generateHubVersionResource)
}

tasks.named<JavaExec>("run") {
  // Run from the project root so relative paths (gradlew, .git) resolve naturally.
  workingDir = rootProject.projectDir
  // Propagate the root into the forked JVM; JvnHub reads this to anchor every
  // child-process (gradlew, git) invocation regardless of where the user launched from.
  systemProperty("jvn.projectRoot", rootProject.projectDir.absolutePath)
  // Keep the launching console quiet: the hub is a GUI.
  standardInput = System.`in`
}

val packagedEngineWorkspaceZip = tasks.register<Zip>("packagedEngineWorkspaceZip") {
  group = "distribution"
  description = "Zips a clean engine workspace for the self-contained Engine Hub jar."
  archiveFileName.set("packaged-engine-workspace.zip")
  destinationDirectory.set(layout.buildDirectory.dir("packaged-engine"))
  isZip64 = true

  from(rootProject.rootDir) {
    into("engine")
    includeEmptyDirs = false
    exclude(
        ".git/**",
        ".gradle/**",
        ".jvn-gradle-user-home/**",
        ".idea/**",
        ".vscode/**",
        "**/.DS_Store",
        "build/**",
        "**/build/**",
        "**/bin/**",
        "**/out/**",
        "**/target/**",
        "**/hs_err_pid*.log",
        "**/*.log",
        "**/.pytest_cache/**",
        "**/__pycache__/**",
        "tools/vscode-jvn/node_modules/**",
        "tools/vscode-jvn/*.vsix",
        "jvn",
        "jvn.bat",
        "jvn.desktop",
        "JVN.command")
  }
}

tasks.register<Jar>("packageEngineHubJar") {
  group = "distribution"
  description = "Builds one launchable jar that bundles the engine workspace and starts the Engine Hub."
  dependsOn(tasks.named("classes"), packagedEngineWorkspaceZip)
  archiveBaseName.set("jvn-engine-hub")
  archiveVersion.set(rootProject.version.toString())
  destinationDirectory.set(rootProject.layout.buildDirectory.dir("distributions"))
  duplicatesStrategy = DuplicatesStrategy.EXCLUDE

  manifest {
    attributes(
        "Main-Class" to "com.jvn.hub.PackagedHubLauncher",
        "Implementation-Title" to "JVN Engine Hub",
        "Implementation-Version" to rootProject.version.toString())
  }

  from(sourceSets.main.get().output)
  from(packagedEngineWorkspaceZip) {
    into("com/jvn/hub")
    rename { "packaged-engine.zip" }
  }
}

val packagedGradleCacheHome = layout.buildDirectory.dir("packaged-gradle-cache/home")

val preparePackagedGradleCache = tasks.register<Exec>("preparePackagedGradleCache") {
  group = "distribution"
  description = "Warms an isolated Gradle user home for the cached Engine Hub jar."
  val cacheHome = packagedGradleCacheHome
  inputs.files(
      rootProject.layout.projectDirectory.file("settings.gradle.kts"),
      rootProject.layout.projectDirectory.file("build.gradle.kts"),
      rootProject.layout.projectDirectory.file("gradle.properties"))
  outputs.dir(cacheHome)

  doFirst {
    delete(cacheHome)
    cacheHome.get().asFile.mkdirs()
  }

  workingDir = rootProject.rootDir
  environment("GRADLE_USER_HOME", cacheHome.get().asFile.absolutePath)
  commandLine(
      if (System.getProperty("os.name").lowercase().contains("win")) "gradlew.bat" else "./gradlew",
      "--no-daemon",
      "--console=plain",
      ":core:compileJava",
      ":fx:compileJava",
      ":audio:compileJava",
      ":scripting:compileJava",
      ":runtime:compileJava",
      ":editor:compileJava",
      ":hub:compileJava")
}

val stripPackagedGradleCache = tasks.register("stripPackagedGradleCache") {
  group = "distribution"
  description = "Removes volatile or machine-local files from the packaged Gradle cache."
  dependsOn(preparePackagedGradleCache)
  val cacheHome = packagedGradleCacheHome
  inputs.dir(cacheHome)
  outputs.dir(cacheHome)

  doLast {
    val home = cacheHome.get().asFile
    delete(
        home.resolve("daemon"),
        home.resolve("notifications"),
        home.resolve("workers"),
        home.resolve("caches/build-cache-1"),
        home.resolve("caches/journal-1"))
    fileTree(home) {
      include("**/*.lock")
      include("**/*.log")
      include("**/gc.properties")
      include("**/fileHashes.lock")
      include("**/executionHistory.lock")
      include("jdks/*.tar.gz")
      include("jdks/*.zip")
    }.files.forEach { delete(it) }
  }
}

val packagedGradleCacheZip = tasks.register<Zip>("packagedGradleCacheZip") {
  group = "distribution"
  description = "Zips the warmed Gradle dependency cache for the cached Engine Hub jar."
  dependsOn(stripPackagedGradleCache)
  archiveFileName.set("packaged-gradle-cache.zip")
  destinationDirectory.set(layout.buildDirectory.dir("packaged-engine"))
  isZip64 = true
  from(packagedGradleCacheHome) {
    into(".jvn-gradle-user-home")
    includeEmptyDirs = false
  }
}

tasks.register<Jar>("packageEngineHubJarWithCache") {
  group = "distribution"
  description = "Builds a launchable Engine Hub jar with the engine workspace and a warmed Gradle cache."
  dependsOn(tasks.named("classes"), packagedEngineWorkspaceZip, packagedGradleCacheZip)
  archiveBaseName.set("jvn-engine-hub-cached")
  archiveVersion.set(rootProject.version.toString())
  destinationDirectory.set(rootProject.layout.buildDirectory.dir("distributions"))
  duplicatesStrategy = DuplicatesStrategy.EXCLUDE

  manifest {
    attributes(
        "Main-Class" to "com.jvn.hub.PackagedHubLauncher",
        "Implementation-Title" to "JVN Engine Hub",
        "Implementation-Version" to rootProject.version.toString())
  }

  from(sourceSets.main.get().output)
  from(packagedEngineWorkspaceZip) {
    into("com/jvn/hub")
    rename { "packaged-engine.zip" }
  }
  from(packagedGradleCacheZip) {
    into("com/jvn/hub")
    rename { "packaged-gradle-cache.zip" }
  }
}
