plugins {
  `java`
  application
}

application {
  mainClass.set("com.jvn.hub.JvnHub")
}

// The hub is intentionally dependency-free: JDK Swing only.
// It shells out to ./gradlew and git as child processes.

// --- Generated version resource ---------------------------------------------
// Writes the project version into a properties file that the hub reads at
// startup so the UI can show "v<version>" without hardcoding it in code.
val generatedVersionDir = layout.buildDirectory.dir("generated-resources/version")

val generateHubVersionResource = tasks.register("generateHubVersionResource") {
  val outputDir = generatedVersionDir
  val versionString = rootProject.version.toString()
  inputs.property("version", versionString)
  outputs.dir(outputDir)
  doLast {
    val target = outputDir.get().asFile.resolve("com/jvn/hub/version.properties")
    target.parentFile.mkdirs()
    target.writeText(
      """
      |# Auto-generated by :hub:generateHubVersionResource. Do not edit by hand.
      |version=$versionString
      |""".trimMargin()
    )
  }
}

sourceSets.named("main") {
  resources.srcDir(generatedVersionDir)
}

tasks.named("processResources") {
  dependsOn(generateHubVersionResource)
}

tasks.named<JavaExec>("run") {
  // Run from the project root so relative paths (gradlew, .git) resolve naturally.
  workingDir = rootProject.projectDir
  // Propagate the root into the forked JVM; JvnHub reads this to anchor every
  // child-process (gradlew, git) invocation regardless of where the user launched from.
  systemProperty("jvn.projectRoot", rootProject.projectDir.absolutePath)
  // Keep the launching console quiet: the hub is a GUI.
  standardInput = System.`in`
}

val packagedEngineWorkspaceZip = tasks.register<Zip>("packagedEngineWorkspaceZip") {
  group = "distribution"
  description = "Zips a clean engine workspace for the self-contained Engine Hub jar."
  archiveFileName.set("packaged-engine-workspace.zip")
  destinationDirectory.set(layout.buildDirectory.dir("packaged-engine"))
  isZip64 = true

  from(rootProject.rootDir) {
    into("engine")
    includeEmptyDirs = false
    exclude(
        ".git/**",
        ".gradle/**",
        ".jvn-gradle-user-home/**",
        ".idea/**",
        ".vscode/**",
        "**/.DS_Store",
        "build/**",
        "**/build/**",
        "**/out/**",
        "**/target/**",
        "**/.pytest_cache/**",
        "**/__pycache__/**",
        "tools/vscode-jvn/node_modules/**",
        "tools/vscode-jvn/*.vsix",
        "jvn",
        "jvn.bat",
        "jvn.desktop",
        "JVN.command")
  }
}

tasks.register<Jar>("packageEngineHubJar") {
  group = "distribution"
  description = "Builds one launchable jar that bundles the engine workspace and starts the Engine Hub."
  dependsOn(tasks.named("classes"), packagedEngineWorkspaceZip)
  archiveBaseName.set("jvn-engine-hub")
  archiveVersion.set(rootProject.version.toString())
  destinationDirectory.set(rootProject.layout.buildDirectory.dir("distributions"))
  duplicatesStrategy = DuplicatesStrategy.EXCLUDE

  manifest {
    attributes(
        "Main-Class" to "com.jvn.hub.PackagedHubLauncher",
        "Implementation-Title" to "JVN Engine Hub",
        "Implementation-Version" to rootProject.version.toString())
  }

  from(sourceSets.main.get().output)
  from(packagedEngineWorkspaceZip) {
    into("com/jvn/hub")
    rename { "packaged-engine.zip" }
  }
}
