#!/usr/bin/env bash
# Fast, Gradle-free source launcher for the dependency-free Swing Engine Hub.
set -euo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." >/dev/null 2>&1 && pwd)"
CACHE_DIR="${JVN_HUB_CACHE_DIR:-$ROOT_DIR/build/hub-fast-launch}"
CLASSES_DIR="$CACHE_DIR/classes"
STAMP_FILE="$CACHE_DIR/compile.stamp"
LOCK_DIR="$CACHE_DIR/compile.lock"
SOURCE_DIR="$ROOT_DIR/modules/hub/src/main/java"
VERSION_FILE="$ROOT_DIR/gradle.properties"
MODE="${JVN_LAUNCH_MODE:-auto}"
FORCE_REBUILD=0
declare -a HUB_ARGS=()

usage() {
  cat <<'EOF'
Usage: ./jvn [--direct|--gradle] [--rebuild-launcher] [hub arguments]

  --direct            Never invoke Gradle. Compile the tiny Swing hub with javac
                      when its source changes, then launch it with java.
  --gradle            Use the original Gradle :hub:run launch path.
  --rebuild-launcher  Recompile the cached direct launcher before starting.

Environment:
  JVN_LAUNCH_MODE=auto|direct|gradle   Startup mode (default: auto).
  JVN_HUB_CACHE_DIR=<path>            Override the compiled launcher cache.

Auto mode prefers the direct launcher and falls back to Gradle only when no
compiler and no valid cached launcher are available.
EOF
}

while (($#)); do
  case "$1" in
    --direct) MODE="direct" ;;
    --gradle) MODE="gradle" ;;
    --rebuild-launcher) FORCE_REBUILD=1 ;;
    -h|--help) usage; exit 0 ;;
    *) HUB_ARGS+=("$1") ;;
  esac
  shift
done

case "$MODE" in
  auto|direct|gradle) ;;
  *) echo "[jvn] error: invalid JVN_LAUNCH_MODE '$MODE' (use auto, direct, or gradle)." >&2; exit 2 ;;
esac

run_gradle() {
  local gradlew="$ROOT_DIR/gradlew"
  [[ -x "$gradlew" ]] || { echo "[jvn] error: executable gradlew not found at $gradlew" >&2; exit 1; }
  exec "$gradlew" -q --console=plain --configuration-cache --max-workers=2 \
    -p "$ROOT_DIR" :hub:run
}

if [[ "$MODE" == "gradle" ]]; then
  run_gradle
fi

needs_compile() {
  [[ "$FORCE_REBUILD" -eq 1 || ! -f "$STAMP_FILE" || ! -f "$CLASSES_DIR/com/jvn/hub/JvnHub.class" ]] && return 0
  [[ "$VERSION_FILE" -nt "$STAMP_FILE" ]] && return 0
  find "$SOURCE_DIR" -type f -name '*.java' -newer "$STAMP_FILE" -print -quit | grep -q .
}

compile_hub() {
  command -v javac >/dev/null 2>&1 || return 1
  local temp_dir version lock_attempt lock_pid
  mkdir -p "$CACHE_DIR"
  for lock_attempt in {1..100}; do
    if mkdir "$LOCK_DIR" 2>/dev/null; then
      printf '%s\n' "$$" > "$LOCK_DIR/pid"
      break
    fi
    lock_pid="$(sed -n '1p' "$LOCK_DIR/pid" 2>/dev/null || true)"
    if [[ "$lock_pid" =~ ^[0-9]+$ ]] && ! kill -0 "$lock_pid" 2>/dev/null; then
      rm -rf "$LOCK_DIR"
      continue
    fi
    sleep 0.1
  done
  if [[ ! -d "$LOCK_DIR" || "$(sed -n '1p' "$LOCK_DIR/pid" 2>/dev/null || true)" != "$$" ]]; then
    echo "[jvn] error: timed out waiting for another launcher compilation." >&2
    return 1
  fi

  # Another launcher may have refreshed the cache while this process waited.
  if [[ "$FORCE_REBUILD" -eq 0 ]] && ! needs_compile; then
    rm -rf "$LOCK_DIR"
    return 0
  fi

  temp_dir="$(mktemp -d "${TMPDIR:-/tmp}/jvn-hub-compile.XXXXXX")"
  trap 'rm -rf "$temp_dir" "$LOCK_DIR"' RETURN
  version="$(sed -nE 's/^[[:space:]]*jvnVersion[[:space:]]*=[[:space:]]*([^[:space:]]+).*$/\1/p' "$VERSION_FILE" | head -n 1)"
  [[ -n "$version" ]] || version="dev"

  mkdir -p "$temp_dir/classes/com/jvn/hub" "$CACHE_DIR"
  if ! javac --release 21 -encoding UTF-8 -d "$temp_dir/classes" \
      "$SOURCE_DIR/com/jvn/hub/JvnHub.java" \
      "$SOURCE_DIR/com/jvn/hub/WindowsSevenHubIconPainter.java"; then
    trap - RETURN
    rm -rf "$temp_dir" "$LOCK_DIR"
    return 1
  fi
  printf '# Generated by scripts/launch-hub.sh\nversion=%s\n' "$version" \
    > "$temp_dir/classes/com/jvn/hub/version.properties"
  rm -rf "$CLASSES_DIR"
  mv "$temp_dir/classes" "$CLASSES_DIR"
  touch "$STAMP_FILE"
  trap - RETURN
  rm -rf "$temp_dir" "$LOCK_DIR"
}

if needs_compile; then
  if ! compile_hub; then
    if [[ "$MODE" == "direct" ]]; then
      echo "[jvn] error: direct mode needs JDK 21 javac to build the launcher cache." >&2
      exit 1
    fi
    echo "[jvn] javac is unavailable; falling back to Gradle." >&2
    run_gradle
  fi
fi

command -v java >/dev/null 2>&1 || {
  if [[ "$MODE" == "auto" ]]; then run_gradle; fi
  echo "[jvn] error: Java 21 or newer is required." >&2
  exit 1
}

# macOS still ships Bash 3.2, where expanding an empty array under nounset can
# fail even when the array was declared. All validation is complete here.
set +u
declare -a JAVA_OPTS=(-XX:+UseSerialGC -XX:TieredStopAtLevel=1)
if [[ -n "${JVN_HUB_JAVA_OPTS:-}" ]]; then
  read -r -a USER_JAVA_OPTS <<< "$JVN_HUB_JAVA_OPTS"
  JAVA_OPTS+=("${USER_JAVA_OPTS[@]}")
fi

exec java \
  -Djvn.projectRoot="$ROOT_DIR" \
  -Djvn.runningFromSource=true \
  "${JAVA_OPTS[@]}" \
  -cp "$CLASSES_DIR" \
  com.jvn.hub.JvnHub "${HUB_ARGS[@]}"
