#JVN Image Tint Tool State
#Tue Mar 10 00:10:25 CET 2026
global.backgroundTag=Was I Write/game/gui/title_screen/title_screen_temporary_bg_-_front.png
global.bgContrast=0.0000
global.bgOverlayBlend=Overlay
global.bgOverlayColor=\#000000
global.bgOverlayOpacity=0.0000
global.bgSaturation=0.0000
global.bgTintBlend=Normal
global.bgTintColor=\#FFFFFF
global.bgTintStrength=0.0000
global.characterTag=audio/bin/main/images/icons/add.png
global.contrast=0.0000
global.exportFormat=Tint Profile
global.filter=
global.hideBackgroundFx=true
global.hideControls=false
global.hideZones=true
global.offsetX=0.0000
global.offsetY=0.0000
global.saturation=0.0000
global.tintColor=\#FFFFFF
global.tintStrength=30.0000
global.zoom=1.0000
