#JVN Image Attributes Tool State
#Tue Mar 10 00:10:26 CET 2026
global.attributeFilter=
global.exportFormat=show + tag + attrs
global.exportTag=game
global.offsetX=0.000
global.offsetY=0.000
global.randomizeMarkedOnly=true
global.selectedTag=Was I Write/game
global.shortforms=\# name \= attributes\n\# happy \= eyes_neutral mouth_smile\n\# upset \= eyes_angry mouth_open
global.tagFilter=
global.typedAttributes=
global.typedRealtime=true
global.zoom=1.000
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.Y29udHJvbHM=base
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.Y2c=bg
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.Y2hhaXI=legs
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.Y2hhcHRlcl9zZWxlY3RfX19pZ25vcmU=base
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.YWNoaWV2ZW1lbnRz=base
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.YWRkaXRpb25z=01
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.YXJtX2JlaGluZA=01
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.YXJtX2Zyb250XzAx=default
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.YXJtX2Zyb250XzAy=adjusting
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.YXNzZXRz=idle
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.YXVkaW8=base
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.Ym9keQ=default
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.Ym9keV9hcm1z=contemplating
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.Ym9va21hcmtz=base
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.YmFy=bottom
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.YnV0dG9u=base
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.YnV0dG9ucw=idle
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.Z2FsbGVyeQ=base
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.Z3Vp=base
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.ZW1vamlz=2hearts
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.ZW1vdGVz=01
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.ZXllcw=base
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.ZmFjZXNfaGVhZHM=default
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.aG9sZGluZ19waG9uZQ=arm
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.aGFuZF9nZXN0dXJl=arm
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.aW1hZ2Vz=base
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.aWNvbnM=001
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.am9objAx=01
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.am9objAy=01
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.am9obl9kb2U=Doe
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.b3ZlcmxheQ=base
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.bGlseV9sYW5nbGV5=Langley
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.bW91dGg=default
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.bm9ybWFs=piece
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.bnVsbA=ref
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.c25vb3Rz=neutral
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.c2Nyb2xsYmFy=bar
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.c2xpZGVy=bar
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.cGF1c2VfbWVudQ=base
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.cGFuZWwwMQ=base
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.cGFuZWwwMg=01
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.cGFuZWwwMw=bg
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.cGFuZWwwNA=edit01
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.cGFuZWwwNg=Arm01
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.cGFuZWxz=base
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.cGhvbmU=nvl
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.cGhvbmVfaWNvbnM=default
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.cGhvbmVfb25fZWFy=arm
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.cGhvbmVfdWlfZWxlbWVudHM=accord
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.cHJvcHM=drink
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.dGFpbF9iZWhpbmQ=default
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.dGFpbF9mcm9udA=leg
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.dGV4dF9oaXN0b3J5=base
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.dGl0bGVfc2NyZWVu=idle
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.dGlsdGVk=piece
tag.V2FzIEkgV3JpdGUvZ2FtZQ.sel.dW5sb2NrZWRfaXRlbXM=base
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.Y29udHJvbHM=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.Y2c=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.Y2hhaXI=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.Y2hhcHRlcl9zZWxlY3RfX19pZ25vcmU=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.YWNoaWV2ZW1lbnRz=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.YWRkaXRpb25z=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.YXJtX2JlaGluZA=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.YXJtX2Zyb250XzAx=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.YXJtX2Zyb250XzAy=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.YXNzZXRz=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.YXVkaW8=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.Ym9keQ=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.Ym9keV9hcm1z=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.Ym9va21hcmtz=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.YmFy=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.YnV0dG9u=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.YnV0dG9ucw=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.Z2FsbGVyeQ=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.Z3Vp=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.ZW1vamlz=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.ZW1vdGVz=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.ZXllcw=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.ZmFjZXNfaGVhZHM=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.aG9sZGluZ19waG9uZQ=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.aGFuZF9nZXN0dXJl=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.aW1hZ2Vz=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.aWNvbnM=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.am9objAx=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.am9objAy=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.am9obl9kb2U=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.b3ZlcmxheQ=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.bGlseV9sYW5nbGV5=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.bW91dGg=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.bm9ybWFs=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.bnVsbA=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.c25vb3Rz=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.c2Nyb2xsYmFy=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.c2xpZGVy=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.cGF1c2VfbWVudQ=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.cGFuZWwwMQ=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.cGFuZWwwMg=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.cGFuZWwwMw=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.cGFuZWwwNA=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.cGFuZWwwNg=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.cGFuZWxz=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.cGhvbmU=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.cGhvbmVfaWNvbnM=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.cGhvbmVfb25fZWFy=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.cGhvbmVfdWlfZWxlbWVudHM=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.cHJvcHM=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.dGFpbF9iZWhpbmQ=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.dGFpbF9mcm9udA=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.dGV4dF9oaXN0b3J5=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.dGl0bGVfc2NyZWVu=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.dGlsdGVk=false
tag.V2FzIEkgV3JpdGUvZ2FtZQ.swap.dW5sb2NrZWRfaXRlbXM=false
