#JVN Layered Image Visualizer State
#Thu Feb 26 21:13:16 CET 2026
global.filter=
global.selectedSet=audio/bin
state.YXVkaW8vYmlu.active.YWxidW0=true
state.YXVkaW8vYmlu.active.aWNvbnM=true
state.YXVkaW8vYmlu.autoExpr=true
state.YXVkaW8vYmlu.charId=bin
state.YXVkaW8vYmlu.crop=100.000
state.YXVkaW8vYmlu.expr=placeholder_add
state.YXVkaW8vYmlu.focusX=50.000
state.YXVkaW8vYmlu.focusY=50.000
state.YXVkaW8vYmlu.groupOrder=YWxidW0,aWNvbnM
state.YXVkaW8vYmlu.matchGameFraming=false
state.YXVkaW8vYmlu.randomActiveOnly=true
state.YXVkaW8vYmlu.sel.YWxidW0=audio/bin/main/images/icons/album_placeholder.png
state.YXVkaW8vYmlu.sel.aWNvbnM=audio/bin/main/images/icons/add.png
state.YXVkaW8vYmlu.zoom=100.000
