#JVN Layered Image Visualizer State
#Tue Mar 10 00:10:25 CET 2026
global.filter=
global.selectedSet=Was I Write/game
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.Y29udHJvbHM=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.Y2c=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.Y2hhaXI=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.Y2hhcHRlcl9zZWxlY3RfX19pZ25vcmU=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.YWNoaWV2ZW1lbnRz=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.YWRkaXRpb25z=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.YXJtX2JlaGluZA=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.YXJtX2Zyb250XzAx=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.YXJtX2Zyb250XzAy=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.YXNzZXRz=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.YXVkaW8=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.Ym9keQ=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.Ym9keV9hcm1z=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.Ym9va21hcmtz=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.YmFy=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.YnV0dG9u=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.YnV0dG9ucw=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.Z2FsbGVyeQ=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.Z3Vp=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.ZW1vamlz=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.ZW1vdGVz=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.ZXllcw=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.ZmFjZXNfaGVhZHM=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.aG9sZGluZ19waG9uZQ=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.aGFuZF9nZXN0dXJl=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.aW1hZ2Vz=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.aWNvbnM=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.am9objAx=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.am9objAy=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.am9obl9kb2U=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.b3ZlcmxheQ=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.bGlseV9sYW5nbGV5=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.bW91dGg=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.bm9ybWFs=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.bnVsbA=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.c25vb3Rz=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.c2Nyb2xsYmFy=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.c2xpZGVy=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.cGF1c2VfbWVudQ=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.cGFuZWwwMQ=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.cGFuZWwwMg=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.cGFuZWwwMw=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.cGFuZWwwNA=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.cGFuZWwwNg=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.cGFuZWxz=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.cGhvbmU=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.cGhvbmVfaWNvbnM=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.cGhvbmVfb25fZWFy=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.cGhvbmVfdWlfZWxlbWVudHM=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.cHJvcHM=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.dGFpbF9iZWhpbmQ=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.dGFpbF9mcm9udA=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.dGV4dF9oaXN0b3J5=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.dGl0bGVfc2NyZWVu=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.dGlsdGVk=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.active.dW5sb2NrZWRfaXRlbXM=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.attributeFilter=
state.V2FzIEkgV3JpdGUvZ2FtZQ.autoExpr=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.charId=game
state.V2FzIEkgV3JpdGUvZ2FtZQ.crop=100.000
state.V2FzIEkgV3JpdGUvZ2FtZQ.expr=base_01_01_default_adjusting_0_base_bottom_default_contemplating_base_base_active_bg_legs_base_base_2hearts_01_base_default_base_base_arm_arm_001_base_01_01_doe_langley_default_piece_ref_base_base_01_bg_edit01_arm01_base_base_nvl_default_arm_accord_drink_bar_bar_neutral_default_leg_base_piece_active_base
state.V2FzIEkgV3JpdGUvZ2FtZQ.focusX=50.000
state.V2FzIEkgV3JpdGUvZ2FtZQ.focusY=50.000
state.V2FzIEkgV3JpdGUvZ2FtZQ.groupOrder=YWNoaWV2ZW1lbnRz,YWRkaXRpb25z,YXJtX2JlaGluZA,YXJtX2Zyb250XzAx,YXJtX2Zyb250XzAy,YXNzZXRz,YXVkaW8,YmFy,Ym9keQ,Ym9keV9hcm1z,Ym9va21hcmtz,YnV0dG9u,YnV0dG9ucw,Y2c,Y2hhaXI,Y2hhcHRlcl9zZWxlY3RfX19pZ25vcmU,Y29udHJvbHM,ZW1vamlz,ZW1vdGVz,ZXllcw,ZmFjZXNfaGVhZHM,Z2FsbGVyeQ,Z3Vp,aGFuZF9nZXN0dXJl,aG9sZGluZ19waG9uZQ,aWNvbnM,aW1hZ2Vz,am9objAx,am9objAy,am9obl9kb2U,bGlseV9sYW5nbGV5,bW91dGg,bm9ybWFs,bnVsbA,b3ZlcmxheQ,cGFuZWwwMQ,cGFuZWwwMg,cGFuZWwwMw,cGFuZWwwNA,cGFuZWwwNg,cGFuZWxz,cGF1c2VfbWVudQ,cGhvbmU,cGhvbmVfaWNvbnM,cGhvbmVfb25fZWFy,cGhvbmVfdWlfZWxlbWVudHM,cHJvcHM,c2Nyb2xsYmFy,c2xpZGVy,c25vb3Rz,dGFpbF9iZWhpbmQ,dGFpbF9mcm9udA,dGV4dF9oaXN0b3J5,dGlsdGVk,dGl0bGVfc2NyZWVu,dW5sb2NrZWRfaXRlbXM
state.V2FzIEkgV3JpdGUvZ2FtZQ.matchGameFraming=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.randomActiveOnly=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.Y29udHJvbHM=Was I Write/game/gui/pause_menu/options/controls/pause_menu_options_-_controls_base.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.Y2c=Was I Write/game/images/CG/pleasant_white_bg.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.Y2hhaXI=Was I Write/game/images/props/chair/chair_legs.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.Y2hhcHRlcl9zZWxlY3RfX19pZ25vcmU=Was I Write/game/gui/pause_menu/general/Chapter_select_-_IGNORE/pause_menu_general_-_chapter_select_base.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.YWNoaWV2ZW1lbnRz=Was I Write/game/gui/pause_menu/general/achievements/pause_menu_general_-_achievements_base.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.YWRkaXRpb25z=Was I Write/game/images/characters/lily_langley/head/normal/additions/Lilily_Langley_normal_additions_-_blush_01.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.YXJtX2JlaGluZA=Was I Write/game/images/characters/lily_langley/arm  behind/Lilily_Langley_arm_behind_-_vague_hold_01.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.YXJtX2Zyb250XzAx=Was I Write/game/images/characters/john_doe/arm front 01/John_Doe_arm_front_01_-_default.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.YXJtX2Zyb250XzAy=Was I Write/game/images/characters/lily_langley/arm front 02/Lilily_Langley_arm_front_-_adjusting.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.YXNzZXRz=Was I Write/game/phone/assets/volume_icon_0.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.YXVkaW8=Was I Write/game/gui/pause_menu/options/Audio/pause_menu_options_-_audio_base.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.Ym9keQ=Was I Write/game/images/characters/john_doe/body/John_Doe_body_-_default.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.Ym9keV9hcm1z=Was I Write/game/images/characters/john_doe/body/body arms/John_Doe_body_arm_-_contemplating.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.Ym9va21hcmtz=Was I Write/game/gui/pause_menu/bookmarks/pause_menu_bookmarks_-_base.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.YmFy=Was I Write/game/gui/bar/bottom.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.YnV0dG9u=Was I Write/game/gui/button/text_box_lower_buttons_-_base.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.YnV0dG9ucw=Was I Write/game/images/buttons/pause_menu_buttons_-_bookmarks_active.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.Z2FsbGVyeQ=Was I Write/game/gui/pause_menu/general/Gallery/pause_menu_general_-_gallery_base.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.Z3Vp=Was I Write/game/gui/text_box_base.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.ZW1vamlz=Was I Write/game/phone/assets/emojis/2hearts.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.ZW1vdGVz=Was I Write/game/images/emotes/emoticons_shock_01.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.ZXllcw=Was I Write/game/images/characters/john_doe/head/eyes/John_Doe_head_-_eyes_base.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.ZmFjZXNfaGVhZHM=Was I Write/game/images/characters/john_doe/head/faces (+heads)/John_Doe_faces_-_default.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.aG9sZGluZ19waG9uZQ=Was I Write/game/images/characters/john_doe/arm behind/holding phone/John_Doe_arm_behind_-_holding_phone_arm.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.aGFuZF9nZXN0dXJl=Was I Write/game/images/characters/john_doe/arm behind/hand gesture/John_Doe_arm_behind_-_hand_gesture_arm.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.aW1hZ2Vz=Was I Write/game/images/chapter_select_base.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.aWNvbnM=Was I Write/game/gui/pause_menu/general/achievements/icons/pause_menu_general_-_achievements_box_icon_-_001.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.am9objAx=Was I Write/game/images/Panels/Panel03/John01/panel_03_cut_01.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.am9objAy=Was I Write/game/images/Panels/Panel03/John02/panel_04_cut_01.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.am9obl9kb2U=Was I Write/game/images/characters/john_doe/John_Doe.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.b3ZlcmxheQ=Was I Write/game/gui/overlay/confirm_base.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.bGlseV9sYW5nbGV5=Was I Write/game/images/characters/lily_langley/Lilily_Langley.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.bW91dGg=Was I Write/game/images/characters/john_doe/head/mouth/John_Doe_mouth_-_default.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.bm9ybWFs=Was I Write/game/images/characters/lily_langley/head/normal/Lilily_Langley_normal_head_-_hair_piece.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.bnVsbA=Was I Write/game/images/characters/john_doe/null/john_doe_null_ref.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.c25vb3Rz=Was I Write/game/images/characters/lily_langley/head/normal/snoots/Lilily_Langley_normal_snoots_-_less_neutral.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.c2Nyb2xsYmFy=Was I Write/game/gui/phone/scrollbar/horizontal_hover_bar.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.c2xpZGVy=Was I Write/game/gui/phone/slider/horizontal_hover_bar.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.cGF1c2VfbWVudQ=Was I Write/game/gui/pause_menu/pause_menu_base.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.cGFuZWwwMQ=Was I Write/game/images/Panels/Panel01/panel_01_base.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.cGFuZWwwMg=Was I Write/game/images/Panels/Panel02/panel_02_base_01.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.cGFuZWwwMw=Was I Write/game/images/Panels/Panel03/panel03_bg.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.cGFuZWwwNA=Was I Write/game/images/Panels/Panel04/Panel04_edit01.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.cGFuZWwwNg=Was I Write/game/images/Panels/Panel06/05_Arm01.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.cGFuZWxz=Was I Write/game/images/Panels/panel_05_base.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.cGhvbmU=Was I Write/game/gui/phone/nvl.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.cGhvbmVfaWNvbnM=Was I Write/game/images/phone_icons/default.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.cGhvbmVfb25fZWFy=Was I Write/game/images/characters/lily_langley/arm front 01/phone on ear/Lilily_Langley_arm_front_-_phone_on_ear_-_arm.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.cGhvbmVfdWlfZWxlbWVudHM=Was I Write/game/images/phone_ui_elements/accord.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.cHJvcHM=Was I Write/game/images/props/energy_drink.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.dGFpbF9iZWhpbmQ=Was I Write/game/images/characters/lily_langley/Body/tail behind/Lilily_Langley_tail_behind_-_default.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.dGFpbF9mcm9udA=Was I Write/game/images/characters/lily_langley/Body/tail front/Lilily_Langley_tail_front_-_wrap_around_leg.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.dGV4dF9oaXN0b3J5=Was I Write/game/gui/pause_menu/general/Text_history/pause_menu_general_-_text_history_base.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.dGl0bGVfc2NyZWVu=Was I Write/game/gui/title_screen/title_screen_temporary_button_-_big_active.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.dGlsdGVk=Was I Write/game/images/characters/lily_langley/head/tilted/Lilily_Langley_tilted_head_-_hair_piece.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.sel.dW5sb2NrZWRfaXRlbXM=Was I Write/game/gui/pause_menu/general/Unlocked_items/pause_menu_general_-_unlocked_items_base.png
state.V2FzIEkgV3JpdGUvZ2FtZQ.shortforms=\# Example\:\n\# happy \= eyes\=neutral mouth\=happy\n\# serious \= eyes\=cross_closed mouth\=neutral
state.V2FzIEkgV3JpdGUvZ2FtZQ.showOverlayGuides=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.snippetFormat=@charimg + [show]
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.Y29udHJvbHM=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.Y2c=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.Y2hhaXI=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.Y2hhcHRlcl9zZWxlY3RfX19pZ25vcmU=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.YWNoaWV2ZW1lbnRz=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.YWRkaXRpb25z=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.YXJtX2JlaGluZA=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.YXJtX2Zyb250XzAx=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.YXJtX2Zyb250XzAy=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.YXNzZXRz=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.YXVkaW8=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.Ym9keQ=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.Ym9keV9hcm1z=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.Ym9va21hcmtz=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.YmFy=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.YnV0dG9u=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.YnV0dG9ucw=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.Z2FsbGVyeQ=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.Z3Vp=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.ZW1vamlz=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.ZW1vdGVz=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.ZXllcw=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.ZmFjZXNfaGVhZHM=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.aG9sZGluZ19waG9uZQ=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.aGFuZF9nZXN0dXJl=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.aW1hZ2Vz=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.aWNvbnM=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.am9objAx=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.am9objAy=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.am9obl9kb2U=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.b3ZlcmxheQ=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.bGlseV9sYW5nbGV5=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.bW91dGg=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.bm9ybWFs=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.bnVsbA=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.c25vb3Rz=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.c2Nyb2xsYmFy=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.c2xpZGVy=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.cGF1c2VfbWVudQ=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.cGFuZWwwMQ=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.cGFuZWwwMg=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.cGFuZWwwMw=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.cGFuZWwwNA=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.cGFuZWwwNg=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.cGFuZWxz=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.cGhvbmU=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.cGhvbmVfaWNvbnM=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.cGhvbmVfb25fZWFy=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.cGhvbmVfdWlfZWxlbWVudHM=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.cHJvcHM=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.dGFpbF9iZWhpbmQ=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.dGFpbF9mcm9udA=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.dGV4dF9oaXN0b3J5=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.dGl0bGVfc2NyZWVu=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.dGlsdGVk=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.swap.dW5sb2NrZWRfaXRlbXM=false
state.V2FzIEkgV3JpdGUvZ2FtZQ.typedAttributes=
state.V2FzIEkgV3JpdGUvZ2FtZQ.typedRealtime=true
state.V2FzIEkgV3JpdGUvZ2FtZQ.zoom=100.000
